apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    instance: {{ .Values.name }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
  ownerReferences:
  - apiVersion: druid.gardener.cloud/v1alpha1
    blockOwnerDeletion: false
    controller: true
    kind: Etcd
    name: {{ .Values.name }}
    uid: {{ .Values.uid }}
spec:
# Note: Changing service type will requre change in handling the re-sync of the service.
  type: ClusterIP
  sessionAffinity: None
  selector:
    instance: {{ .Values.name }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
  ports:
  - name: client
    protocol: TCP
    port: {{ .Values.etcd.clientPort }}
    targetPort: {{ .Values.etcd.clientPort }}
  - name: server
    protocol: TCP
    port: {{ .Values.etcd.serverPort }}
    targetPort: {{ .Values.etcd.serverPort }}
  - name: backuprestore
    protocol: TCP
    port: {{ .Values.backup.port }}
    targetPort: {{ .Values.backup.port }}