apiVersion: v1
kind: Service
metadata:
  name: {{ required "Values.serviceName is required" .Values.serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    instance: {{ required "Values.name is required" .Values.name }}
    scope: internal
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
  ownerReferences:
  - apiVersion: druid.gardener.cloud/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Etcd
    name: {{ required "Values.name is required" .Values.name }}
    uid: {{ required "Values.uid is required" .Values.uid }}
spec:
# Note: Changing service type will require change in handling the re-sync of the service.
  type: ClusterIP
  ClusterIP: None
  sessionAffinity: None
  selector:
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
  ports:
  - name: etcd-client
    protocol: TCP
    port: {{ required "Values.etcd.clientPort is required" .Values.etcd.clientPort }}
    targetPort: {{ required "Values.etcd.clientPort is required" .Values.etcd.clientPort }}
  - name: etcd-server
    protocol: TCP
    port: {{ required "Values.etcd.serverPort is required" .Values.etcd.serverPort }}
    targetPort: {{ required "Values.etcd.serverPort is required" .Values.etcd.serverPort }}
  - name: backuprestore
    protocol: TCP
    port: {{ required "Values.backup.port is required" .Values.backup.port }}
    targetPort: {{ required "Values.backup.port is required" .Values.backup.port }}