crds:
  enabled: true
image:
  repository: europe-docker.pkg.dev/gardener-project/public/gardener/etcd-druid
  tag: latest
  imagePullPolicy: IfNotPresent
replicas: 1
ignoreOperationAnnotation: false
# enableBackupCompaction: true
# eventsThreshold: 15
# metricsScrapeWaitDuration: "10s"
# featureGates:
#   UseEtcdWrapper: true

server:
  webhook:
    bindAddress: ""
    port: 9443
    tls:
      serverCertDir: /etc/webhook-server-tls

enableSentinelWebhook: true
