name: Build
on:
  push:
    branches:
      - master
      - 'hotfix-**'
      - 'release-**'
  pull_request_target:
    types:
      - labeled

jobs:
  build:
    uses: ./.github/workflows/base.yaml
    with:
      mode: snapshot
    secrets: inherit
    if: ${{ github.event.action != 'labeled' || github.event.label.name == 'ok-to-test' }}
    permissions:
      pull-requests: write
      contents: read
      packages: write
      id-token: write

  component-descriptor:
    uses: gardener/cc-utils/.github/workflows/post-build.yaml@master
    needs:
      - build
    secrets: inherit
    if: ${{ github.event.action != 'labeled' || github.event.label.name == 'ok-to-test' }}
    permissions:
      id-token: write
      contents: write
