name: Build
on:
  push:
    branches:
      - master
      - 'hotfix-**'
      - 'release-**'
  pull_request_target:

jobs:
  build:
    uses: ./.github/workflows/base.yaml
    with:
      mode: snapshot
      run-tests: true
    secrets: inherit
    permissions:
      contents: read
      packages: write
      id-token: write

  component-descriptor:
    uses: gardener/cc-utils/.github/workflows/post-build.yaml@master
    needs:
      - build
    secrets: inherit
    permissions:
      id-token: write
      contents: write
