on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  pullrequest-trusted-helper:
    permissions:
      id-token: write
    uses: gardener/cc-utils/.github/workflows/pullrequest-trust-helper.yaml@master
    with:
      # members will be trusted (-> get okay-to-test-label automatically)
      trusted-teams: "core,etcd-druid-maintainers"
