on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  pullrequest-trusted-helper:
    permissions:
      pull-requests: write
    secrets: inherit # access to `GitHub-Actions`-App is needed to read teams
    uses: gardener/cc-utils/.github/workflows/pullrequest-trust-helper.yaml@master
    with:
      # members will be trusted (-> get okay-to-test-label automatically)
      trusted-teams: "core,etcd-druid-maintainers"
