name: Create Upgrade-Pull-Requests
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  upgrade-pullrequests:
    uses: gardener/cc-utils/.github/workflows/upgrade-dependencies.yaml@master
    permissions:
      contents: read
      id-token: write
